# Generated by Django 2.2.1 on 2019-05-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nosologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Номер')),
                ('name', models.CharField(max_length=150, verbose_name='Заболевание')),
                ('mkbFirst', models.CharField(max_length=6, verbose_name='с_МКБ')),
                ('mkbLast', models.CharField(max_length=6, verbose_name='по_МКБ')),
            ],
            options={
                'db_table': '"NSLGS"',
            },
        ),

    ]
